#!name=🎬 YouTube Premium Unlock By Anh Tuan
#!desc=Block Ads + Unlock Background Play, PiP & High Resolution
#!author=Anh Tuan
#!version=1.0.0
#!date=2025-08-22
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

[MITM]
hostname = %APPEND% *.googlevideo.com, www.youtube.com, s.youtube.com, youtubei.googleapis.com, adservice.google.com, securepubads.g.doubleclick.net

[Rule]
# Chặn quảng cáo từ YouTube & Google Ads
AND,((DOMAIN-SUFFIX,googlevideo.com), (PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com), (PROTOCOL,UDP)),REJECT
DOMAIN-SUFFIX,ads.youtube.com,REJECT
DOMAIN-SUFFIX,adservice.google.com,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,googleads.g.doubleclick.net,REJECT

[URL Rewrite]
# Bỏ query quảng cáo & thống kê
(^https?://[\w-]+\.googlevideo\.com/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
^https?://[\w-]+\.googlevideo\.com/(?!(dclk_video_ads|videoplayback?)).+&oad _ reject-200
^https?://(www|s)\.youtube\.com/api/stats/ads _ reject-200
^https?://(www|s)\.youtube\.com/(pagead|ptracking) _ reject-200
^https?://s\.youtube\.com/api/stats/qoe\?adcontext _ reject-200
^https?://(www|s)\.youtube\.com/get_midroll_info _ reject-200
^https?://(www|s)\.youtube\.com/get_vmap _ reject-200

[Script]
# YouTube Unlock (Adblock + PIP + Background + Resolution)
youtube.response = type=http-response,pattern=^https://youtubei\.googleapis\.com/youtubei/v1/(browse|next|player|search|reel/reel_watch_sequence|guide|account/get_setting|get_watch),requires-body=1,max-size=-1,engine=script,timeout=60,script-path=https://raw.githubusercontent.com/ng-anhtuan/modules-shadowrocket/refs/heads/main/js/youtube/youtube.js,argument="{\"enablePIP\":true,\"enableBackgroundPlay\":true,\"unlockResolution\":true,\"debug\":false}"
