#!name=🎬 YouTube Premium Unlock
#!desc=Unlock Background Play, PiP + Block Ads
#!author=Anh Tuan
#!version=1.0.0
#!date=2025-08-22
#!icon=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png

[MITM]
hostname = %APPEND% youtubei.googleapis.com, www.youtube.com, s.youtube.com, *.googlevideo.com, adservice.google.com, securepubads.g.doubleclick.net

[Rule]
DOMAIN-SUFFIX,ads.youtube.com,REJECT
DOMAIN-SUFFIX,adservice.google.com,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,googlesyndication.com,REJECT
DOMAIN-SUFFIX,googleads.g.doubleclick.net,REJECT

[URL Rewrite]
# Một số endpoint quảng cáo → reject 200
^https?://(www|s)\.youtube\.com/(pagead|ptracking|api/stats/ads) _ reject-200
^https?://s\.youtube\.com/api/stats/qoe\?adcontext _ reject-200
^https?://(www|s)\.youtube\.com/get_midroll_info _ reject-200
^https?://(www|s)\.youtube\.com/get_vmap _ reject-200

[Script]
youtube = type=http-response,pattern=^https://youtubei\.googleapis\.com/youtubei/v1/(browse|next|player|search|reel/reel_watch_sequence|guide|account/get_setting|get_watch),requires-body=1,max-size=-1,engine=script,timeout=60,script-path=https://raw.githubusercontent.com/ng-anhtuan/modules-shadowrocket/refs/heads/main/js/youtube/youtube.js
